Wrap calls to ga check for analytics_tracking_id
silinternational/ssp-base pull request #290
Opened 2024-11-13 22:11 UTC by jason-jackson

### Changed
- Wrap calls to ga check for analytics_tracking_id

2024-11-14 02:06 UTC, briskt approved these changes
Great job hunting down all the uses of `ga`!

2024-11-14 02:07 UTC, briskt commented
I'm surprised ga is not defined since we should be providing the tracking ID in all IdPs. There may be something else wrong with the ga library.

2024-11-14 02:08 UTC, briskt commented
I saw that @forevermatt marked GA as deprecated in idp-id-broker. Maybe he or @devon-sil can comment about its use here.

2024-11-15 18:52 UTC, forevermatt commented
> I saw that @forevermatt marked GA as deprecated in idp-id-broker. Maybe he or @devon-sil can comment about its use here.

In ID Broker, I was deprecating the use of Google Analytics for reporting MFA metrics (server side, from a cron job). This all looks like client-side reporting, but I don't know if we still use that, either. 🤷

2024-11-18 14:08 UTC, mtompset commented on modules/material/themes/material/silauth/loginuserpass.twig
> +          {% if analytics_tracking_id is not empty %}
I feel like @forevermatt wanting an abstraction to make the sense of these "is not empty" clearer, even though I know what it is.

2024-11-26 22:20 UTC, hobbitronics requested changes
I am finding `ga` is undefined, but in header.twig gtag is defined and has a slightly different api which looks like:
      gtag('event', 'IdP', {
        'event_category': 'hub',
        'event_label': 'choice',
        'value': id
      });

2024-11-26 22:20 UTC, hobbitronics commented on modules/material/themes/material/default/selectidp-links.twig
> +        ga('send', 'event', 'hub', 'choice', 'IdP', id);
I think this should be 
      gtag('event', 'IdP', {
        'event_category': 'hub',
        'event_label': 'choice',
        'value': id
      });

2024-11-28 04:55 UTC, merged